[project]
name = 'Cosmic-Archaeology-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.mission-funding]
path = 'contracts/mission-funding.clar'
clarity_version = 2
epoch = 2.5

[contracts.peer-review]
path = 'contracts/peer-review.clar'
clarity_version = 2
epoch = 2.5

[contracts.research-management]
path = 'contracts/research-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
